fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .vscode
      - id: end-of-file-fixer
      - id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.6'
    hooks:
      - id: clang-format
        exclude_types: [javascript, json]
